WebProveedores/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProveedores.Models.Data;

namespace WebProveedores.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ProductoController> _logger;

        public ProductoController(ApplicationDbContext context, ILogger<ProductoController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index(int? id)
        {

            if (id == null)
            {
                var productosTodos = _context.Productos.Include(p => p.Proveedor);
                return View(productosTodos.ToList());
            }

            var proveedor = _context.Proveedores.Where(w => w.IdProveedor == id).FirstOrDefault();
            ViewData["ProveedorCodigo"] = proveedor.Codigo;
            ViewData["ProveedorId"] = proveedor.IdProveedor;

            var productos = _context.Productos.Where(w => w.IdProveedor == id);
            return View(productos.ToList());

        }


        public IActionResult Create(int? id)
        {
            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "Codigo", id);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Producto producto)
        {

            if (ModelState.IsValid)
            {
                var codigoExistente = _context.Productos.Where(w => w.Codigo == producto.Codigo && w.IdProveedor == producto.IdProveedor).FirstOrDefault();
                if (codigoExistente == null)
                {
                    _logger.LogWarning("[ProductoController] [Create] - Codigo ya existe");
                    ModelState.AddModelError("Codigo", "Ya existe un producto con este codigo.");
                    return View(producto);

                }

                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                foreach (var item in errors)
                {
                    _logger.LogCritical("[ProductoController] [Create] - error al intentar crear un producto {" + item.FirstOrDefault().ErrorMessage + "}");

                }

            }

            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "Codigo", producto.IdProveedor);
            return View(producto);
        }


    }
}

WebProveedores/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Mvc;
using WebProveedores.Models.Data;

namespace WebProveedores.Controllers
{
    public class ProveedorController : Controller
    {
        private ApplicationDbContext _context;
        private readonly ILogger<ProveedorController> _logger;

        public ProveedorController(ApplicationDbContext context, ILogger<ProveedorController> logger)
        {
            _context = context;
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View(_context.Proveedores.ToList());
        }

        public IActionResult Create()
        {
            return View(new Proveedor());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Proveedor proveedor)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                foreach (var item in errors)
                {
                    _logger.LogCritical("[ProveedorController] [Create] - error al intentar crear un proveedor {" + item.FirstOrDefault().ErrorMessage + "}");

                }

                return View(proveedor);
            }

            var codigoExistente = _context.Proveedores.Where(w => w.Codigo == proveedor.Codigo).FirstOrDefault();
            if (codigoExistente != null)
            {
                ModelState.AddModelError("Codigo", "Ya existe un proveedor con este codigo.");
                return View(proveedor);

            }

            _context.Proveedores.Add(proveedor);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var proveedor = _context.Proveedores.Where(w => w.IdProveedor == id).FirstOrDefault();
            if (proveedor == null)
            {
                _logger.LogWarning("[ProveedorController] [Edit] - No encontro ID para editar");
                return NotFound();
            }

            return View(proveedor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Proveedor proveedor)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();

                foreach (var item in errors)
                {
                    _logger.LogCritical("[ProveedorController] [Edit] - error al intentar crear un proveedor {" + item.FirstOrDefault().ErrorMessage + "}");

                }
                return View(proveedor);
            }

            _context.Proveedores.Update(proveedor);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            var proveedor = _context.Proveedores.FirstOrDefault(w => w.IdProveedor == id);
            if (proveedor == null)
            {
                _logger.LogWarning("[ProveedorController] [Delete] - No encontro ID para eliminar");
                return NotFound();
            }

            bool tieneProductos = _context.Productos.Any(p => p.IdProveedor == id);
            if (tieneProductos)
            {
                return RedirectToAction("ConfirmDelete", new { id = proveedor.IdProveedor });
            }
            else
            {
                _context.Proveedores.Remove(proveedor);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }


        public IActionResult ConfirmDelete(int id)
        {
            var proveedor = _context.Proveedores.FirstOrDefault(w => w.IdProveedor == id);
            if (proveedor == null)
            {
                _logger.LogWarning("[ProveedorController] [ConfirmDelete] - No encontro ID para eliminar");
                return NotFound();
            }

            return View(proveedor);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDeleteConfirmed(int id)
        {
            var proveedor = _context.Proveedores.FirstOrDefault(w => w.IdProveedor == id);
            if (proveedor != null)
            {
                _logger.LogWarning("[ProveedorController] [ConfirmDeleteConfirmed] - No encontro ID para eliminar");
                return NotFound();
            }

            _context.Proveedores.Remove(proveedor);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebProveedores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProveedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProveedores.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProveedores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebProveedores 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>